on:
  release:
    types: [created]
    
jobs:
  release:
    name: Release and publish

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the versions bump
      contents: write

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/checkout@v2
      
      - name: Install dependencies & publishing tools
        run: |
          npm install
          npm install -g @vscode/vsce ovsx
      
      # - name: Bump version numbers
      #   run: |
      #     npm --no-git-tag-version version ${{ github.ref_name }}
      #     cd types && npm --no-git-tag-version version ${{ github.ref_name }}

      # - name: Commit & push versions bump
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     branch: master
      #     commit_message: Released version ${{ github.ref_name }}

      - name: Publish to Marketplace
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          
      - name: Publish to Open VSX
        run: npx ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}

      - name: Generate typings
        run: npm run typings

      - name: Cleanup typings
        run: cd types && npm run prepublish

      - name: Publish typings to npm
        run: cd types && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}